version: '3.7'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ms-pagamentos
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoExpress2019
    links:
      - mongo
    networks:
      - fiap-network
  mongo:
    image: 'mongo'
    container_name: 'mongo'
    hostname: 'mongo'
    volumes:
      - /usr/local/var/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - fiap-network
    restart: unless-stopped
  
  ms-pagamento:
    build:
      context: .
      dockerfile: Dockerfile
    image: rodrigoamora/rodrigo-springboot
    container_name: 'ms-pagamento'
    hostname: 'ms-pagamento'
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/pagamentos
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
    ports:
      - "8080:8080"
    networks:
      - fiap-network
    depends_on:
      - mongo
    links:
      - mongo

networks:
  fiap-network:
    driver: bridge

volumes:
  mongodb_data:
