codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: [60.0, 80.0]

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 5%

github_checks:
  annotations: false

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
